### ISSUE TITLE
Une version Team du TNTGame

### ISSUE THREAD

**Issue by RedNesto** [PixHellFR/Issues#1]
Cette suggestion s'adresse surtout à @Elikill58.

Cette version aurait 2 ou 3 teams de 2 à 4 joueurs (par rapport à la taille de la map).
Il n'y aurait pas de friendly fire.
On pourrait rejoindre une team au hasard, au choix et même inviter quelqu'un dans sa team.

**Comment by Elikill58** [comment]
@RedNesto : j'vais voir ça

**Comment by Elikill58** [comment]
Fini. (Y'a pas de label pour ça @RedNesto koman on en add ?

**Comment by RedNesto** [comment]
Il suffit de fermer ;)
